name: todo
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+000001

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  hive: ^2.0.4
  path_provider: ^2.0.5
  google_fonts: ^2.1.0
  automatic_animated_list: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true